# Generated by Django 5.1.1 on 2024-11-21 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='vinyl_audio/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('vinyl_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='catalogue.vinylrecord')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
                'ordering': ['title'],
            },
        ),
    ]
